version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install from pypi
          command: |
            . venv/bin/activate
            pip install DNASpiderWeb

      - run:
          name: check style
          command: |
            . venv/bin/activate
            pycodestyle --ignore=E501,E203,E731,W503,W292 *.py */*py
            pip install .

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            nosetests -v

      - store_artifacts:
          path: test-reports
          destination: test-reports